config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'signup' => 'users#new'
  resources :users
  resources :orders
  resources :orderlists

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'cart' => 'carts#index'

  root  'products#index'

  get 'management' => 'managements#index'
  get 'management/members' => 'managements#m_members', as: :m_members
  get 'management/products' => 'managements#m_products', as: :m_products
  get 'management/orderlists' => 'managements#m_orderlists', as: :m_orderlists

  get 'user/:id/change_inform' => 'users#change_inform', as: :change_inform
  get 'user/:id/orders_of_user' => 'users#orders_of_user', as: :orders_of_user

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	belongs_to :orderlist
end

app/models/orderlist.rb
class Orderlist < ActiveRecord::Base
	has_many :orders , dependent: :destroy 
	belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders , dependent: :destroy

	validates_presence_of :name,:image, :amount,:price
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	def is_supervisor?
		self.role == "supervisor"
	end


	has_many :orders , dependent: :destroy
	has_many :orderlists, dependent: :destroy

	validates_presence_of :first_name,:last_name,:password_digest,:email
	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def require_supervisor
    if current_user != nil
      redirect_to root_path unless current_user.is_supervisor?
    else
      redirect_to root_path
    end
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :require_user, only: [:index]

	def index
		@user = User.find_by_id( session[:user_id])
		@orders = @user.orders.where( status: "In cart" )
		@total = 0
	end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
	before_action :require_supervisor


	def index
	end

	def m_products
		@products = Product.all
	end

	def m_members
		@members = User.all
	end

	def m_orderlists
		@orderlists = Orderlist.all
	end
end

app/controllers/orderlists_controller.rb
class OrderlistsController < ApplicationController
	def create
		@user = User.find_by_id( session[:user_id])
		@orders = @user.orders.where( status: "In cart" )
		@orderlist = Orderlist.create( order_time: Time.now)

		@orders.each do |order|
			order.status = "Order Determined"

			@orderlist.orders << order
			@user.orderlists << @orderlist
			@orderlist.save
		end

		redirect_to root_path
	end

	def show
		@total = 0 
		@orderlist = Orderlist.find(params[:id])
	end

	def destroy
		@orderlist = Orderlist.find( params[:id])
		@orderlist.destroy
		redirect_to m_orderlists_path
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :require_user

	def destroy
		@order = Order.find( params[:id])
		@order.destroy
		redirect_to :back
	end

	def new
		@product = Product.find( session[:product_id])
		if @product.amount > 0
			@order = Order.new
		else
			redirect_to root_path
		end
	end

	def create
		@order = Order.new( params.require(:order).permit( :number, :user_id, :product_id) )
		if @order.save
			redirect_to root_path
		else
			render 'new'
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find( params[:id] )
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		if @product.update( params.require(:product).permit( :name,  :image, :amount, :price) )
			redirect_to m_products_path
		else
			render 'edit'
		end
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new( params.require(:product).permit(:name,:image,:amount,:price))
		if @product.save
			redirect_to m_products_path
		else
			render 'new'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to m_products_path
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email( params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			render 'new'
		end
	end
	
	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



	def new
		@user = User.new
	end
	
	def show
	end

	def change_inform
		@user = User.find(params[:id])
	end

	def orders_of_user
		@user = User.find(params[:id])
		@orderlists = @user.orderlists
	end

	def update
		@user = User.find(params[:id])
		if @user.update( params.require(:user).permit(:role,:first_name,:last_name,:email))
			redirect_to :back
		else 
			render 'edit'
		end
	end
	def create
		@user = User.new( user_params )
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		@user = User.find_by_id(params[:id])
		@user.destroy
		redirect_to m_members_path
	end
	
	def edit
		@user = User.find_by_id(params[:id])
		@select = ["supervisor","admin"]
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/orderlists_helper.rb
module OrderlistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<div id="cart">
	<h2>Cart</h2>
	<ul class="cart-items">
		<% @orders.each do |order| %>
			<li><%= order.number.to_s + " x " +order.product.name%> 
			<div class='p-price'> <%= "$ "+(order.number*order.product.price).to_s %></div>
			<% @total =@total + (order.number*order.product.price) %>
			<%= button_to "delete",  order_path(order), :method => :delete %>
			</li>
		<% end %>
	</ul>
	<h2><%= "Total: $" + " " +@total.to_s %></h2>
	<div class="list-form">
		<% if @total > 0 %>
			<%= button_to "Order!",  orderlists_path  %>
		<%end%>
	</div>
</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="pull-right">
	<% if current_user %>
		<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Cart", cart_path %> 

		<li class='management'><% if current_user.is_supervisor?  %>
			<%= link_to "Management" , management_path %>
			<% end %>
		</li>

		<li class='user_logout'><%= link_to "Log out", logout_path, method: "delete" %> </li>
		<li class='user_logout'><%= link_to (current_user.first_name + "_" + current_user.last_name) , user_path(current_user) %></li>
		</ul>
	<% else %>
		<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Login",  login_path %></li>
		<li><%= link_to "Signup", signup_path %></li>
		</ul>

	<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/managements/index.html.erb
<div class="management-menu">
	<ul>
		<li><%= link_to "Members", m_members_path  %></li>
		<li><%= link_to "Products", m_products_path  %></li>
		<li><%= link_to "OrderLists", m_orderlists_path  %></li>
	</ul>
</div>

app/views/managements/m_members.html.erb
<div class="management-menu">
	<ul>
		<li><%= link_to "Members", m_members_path  %></li>
		<li><%= link_to "Products", m_products_path  %></li>
		<li><%= link_to "OrderLists", m_orderlists_path  %></li>
	</ul>
</div>

<table class="table-bordered" >
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Email</th>
			<th>Role</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<% @members.each do |member| %>
		<tr>
			<td><%= member.id %></td>
			<td><%= member.first_name+"_"+member.last_name %> </td>
			<td><%= member.email %> </td>
			<td><%= member.role %> </td>
			<% if not member.is_supervisor? %>
			<td><%= link_to "edit", edit_user_path(member) %> </td>
			<td><%= link_to "Delete", user_path(member), method: "delete" %></td>
			<% else %>
				<td></td>
				<td></td>
			<%end%>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/managements/m_orderlists.html.erb
<div class="management-menu">
	<ul>
		<li><%= link_to "Members", m_members_path  %></li>
		<li><%= link_to "Products", m_products_path  %></li>
		<li><%= link_to "OrderLists", m_orderlists_path  %></li>
	</ul>
</div>

<table class="table-bordered" >
	<thead>
		<tr>
			<th>#</th>
			<th>Subcriber</th>
			<th>Order time</th>
			<th>Edit</th>
		</tr>
	</thead>
	<tbody>
		<% @orderlists.each do |orderlist| %>
		<tr>
			<td><%= link_to orderlist.id, orderlist_path(orderlist), {:class => "orderlist-link"} %></td>
			<td><%= orderlist.user.first_name+"_"+orderlist.user.last_name %> </td>
			<td><%= orderlist.order_time %> </td>
			<td><%= "edit" %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/managements/m_orders.html.erb
<div class="management-menu">
	<ul>
		<li><%= link_to "Members", m_members_path  %></li>
		<li><%= link_to "Products", m_products_path  %></li>
		<li><%= link_to "Orders", m_orders_path  %></li>
	</ul>
</div>

<table class="table-bordered" >
	<thead>
		<tr>
			<th>#</th>
			<th>Product</th>
			<th>Subcriber</th>
			<th>Status</th>
			<th>Edit</th>
		</tr>
	</thead>
	<tbody>
		<% @orders.each do |order| %>
		<tr>
			<td><%= order.id %></td>
			<td><%= order.product.name %> </td>
			<td><%= order.user.first_name+"_"+order.user.last_name %> </td>
			<td><%= order.status %> </td>
			<td><%= "edit" %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/managements/m_products.html.erb
<div class="management-menu">
	<ul>
		<li><%= link_to "Members", m_members_path  %></li>
		<li><%= link_to "Products", m_products_path  %></li>
		<li><%= link_to "OrderLists", m_orderlists_path  %></li>
	</ul>
</div>

<table class="table-bordered" >
	<thead>
		<tr>
			<th>#</th>
			<th>Product</th>
			<th>Price</th>
			<th>Amount</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= product.id %></td>
			<td><%= product.name %> </td>
			<td><%= product.price %> </td>
			<td><%= product.amount %> </td>
			<td><%=link_to "edit", edit_product_path(product) %> </td>
			<td><%=link_to "delete", product_path(product) , method: "delete"%> </td>
		</tr>
		<% end %>
	</tbody>
</table>

<div class='create-product'>
	<%= link_to "Make New Product" , new_product_path %>
</div>

app/views/orderlists/show.html.erb
<table class="table-bordered" >
	<thead>
		<tr>
			<th>#</th>
			<th>Subcriber</th>
			<th>Product</th>
			<th>Price</th>
			<th>Number</th>
			<th>Status</th>
			<th>Edit</th>
		</tr>
	</thead>
	<tbody>
		<% @orderlist.orders.each do |order| %>
		<tr>
			<td><%= order.id%></td>
			<td><%= order.user.first_name+"_"+order.user.last_name %> </td>
			<td><%= order.product.name%></td>
			<td><%= order.product.price%> </td>
			<td><%= order.number%> </td>
			<td><%= order.status %> </td>
			<td><%= "edit" %> </td>
			<% @total = @total + order.number*order.product.price %>
		</tr>
		<% end %>
	</tbody>
</table>

<h2><%= "Total: $" + " " +@total.to_s %></h2>

<div class="list-form">
	<%= link_to "Back",  m_orderlists_path  %>
</div>

app/views/orders/new.html.erb
<div class="form">
	<h1> Order </h1>
	<%= form_for (@order), :url => orders_path do |f| %>
		<%= image_tag @product.image%>
		<%= @product.name %>
		<%= f.number_field :number, :placeholder => "How many do you want", min: 1, max: @product.amount %>
		<%= f.hidden_field :user_id, :value => session[:user_id] %>
		<%= f.hidden_field :product_id, :value => session[:product_id] %>
		<%= f.submit "Add into your cart" %>
	<% end %>
</div>

app/views/products/edit.html.erb
<div class="form">
<%= form_for(@product) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> 
	<%= f.label :image %>
	<%= f.text_field :image %> 
	<div id='form-img'> <%= image_tag @product.image %> </div>
	<%= f.label :amount%>
	<%= f.number_field :amount, min: 0 %>
	<%= f.label :price%>
	<%= f.number_field :price, min: 0 %>

	<%= f.submit "Update" %> 
<% end %>
</div>

app/views/products/index.html.erb
<div class= 'img-container' >
<ul>
<% @products.each do |product|%>

	<div class= 'product-img' >
		<li><%= image_tag product.image %></li>
		<h2><%= link_to product.name , product_path(product) %> </h2>
	</div>
	
<% end %>
</ul>
</div>

app/views/products/new.html.erb
<div class="form">
<%= form_for(@product) do |f| %>
	<%= f.label :name,"Product Name" %>
	<%= f.text_field :name %> 
	<%= f.label :image, "Image Link" %>
	<%= f.text_field :image %> 
	<%= f.label :amount, "Amount"%>
	<%= f.number_field :amount, min: 0 %>
	<%= f.label :price, "Price"%>
	<%= f.number_field :price, min: 0 %>

	<%= f.submit "Create" %> 
<% end %>
</div>

app/views/products/show.html.erb
<% session[:product_id] = @product.id %>

<div id="product_name" >
	<h2><%= @product.name %> </h2>
</div>

<div class= 'img-container' >
	<%= image_tag @product.image %>
</div>

<h2><%= "Price: " + " " + @product.price.to_s %> </h2>
<h2><%= "Amount: " + " " + @product.amount.to_s %> </h2>

<% if current_user && @product.amount > 0 %>
	<%= link_to "Buy this!" , new_order_path %>
<% end %>

app/views/users/change_inform.html.erb
<div class="form" >
<%= form_for(@user) do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	

	<%= f.submit "Update" %>
<% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
	<h3> Name: </h3> 
	<%=  @user.first_name + @user.last_name %>
	<h3>Email: </h3> 
	<%= f.label :email, @user.email %>
	<h3> Role:  <%= f.select :role ,  @select  %></h3> 
	
	<%= f.hidden_field :first_name %>
	<%= f.hidden_field :last_name %>

	<%= f.submit "Update" %>
<% end %>

app/views/users/new.html.erb
<div class="form">
	<h1> Sign up </h1>
	<%= form_for (@user) do |f| %>
		<%= f.text_field :first_name, :placeholder => "First name" %>
		<%= f.text_field :last_name, :placeholder => "Last name" %>
		<%= f.email_field :email, :placeholder => "Email" %>
		<%= f.password_field :password, :placeholder => "Password" %>
		<%= f.submit "Create an account" %>
	<% end %>
</div>

app/views/users/orders_of_user.html.erb
<table class="table-bordered" >
	<thead>
		<tr>
			<th>#</th>
			<th>Subcriber</th>
			<th>Order time</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<% @orderlists.each do |orderlist| %>
		<tr>
			<td><%= link_to orderlist.id, orderlist_path(orderlist), {:class => "orderlist-link"} %></td>
			<td><%= orderlist.user.first_name+"_"+orderlist.user.last_name %> </td>
			<td><%= orderlist.order_time %> </td>
			<td><%=link_to "delete", orderlist_path(orderlist) , method: "delete"%> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/show.html.erb
<div class="profile-menu">
	<ul>
		<li><%= link_to "Account Information Change", change_inform_path  %></li>
		<li><%= link_to "Orders", orders_of_user_path  %></li>
	</ul>
</div>